### ISSUE TITLE
Add final modifiers to the code style

### ISSUE THREAD

**Issue by jarekankowski** [ustwo/android-boilerplate#19]
Add final modifier to generated local variables and params

**Comment by mshipton** [comment]
Since we have `.idea` project files committed we can setup AS to do this for us when auto-generating code.

**Comment by jarekankowski** [comment]
Exactly

**Comment by Numan1617** [comment]
@jarekankowski Can you expand on your definition of what you mean by generated local variables and params to ensure my understanding of your use case is correct.

My assumption is you mean the checkbox shown in the screenshot which I'm not aware of a setting for checking it by default.
<img width="307" alt="screen shot 2016-12-11 at 23 52 16" src="https://cloud.githubusercontent.com/assets/3454441/21084540/febfbda2-bffc-11e6-8dd5-e60f76e48883.png">

**Comment by mshipton** [comment]
@Numan1617 I was referring to this: `Editor > Code Style > Java`

![image](https://cloud.githubusercontent.com/assets/302717/21094329/73337588-c04e-11e6-9cd2-bb84acf350da.png)

**Comment by jarekankowski** [comment]
@Numan1617 it was exactly what @mshipton explained. Thank you @mshipton
